=== Vasolik/AcsGenerator/AcsGenerator/layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  targetNamespace="http://www.vipl.in.rs/layout" 
            elementFormDefault="qualified"
            xmlns="http://www.vipl.in.rs/layout"
            xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Main" type="Main"/>
  <xs:complexType name="LogicalElement">
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="VisualOrganizationGroup">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element type="SixPackLayout" name="SixPackLayout"  />
        <xs:element type="NormalLayout" name="NormalLayout" />
        <xs:element type="ThreePackLayout" name="ThreePackLayout"  />
        <xs:element type="StarLayout" name="StarLayout" />
        <xs:element type="SkillLayout" name="SkillLayout"/>
        <xs:element type="CustomLayout" name="CustomLayout"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="localization" use="required"/>
  </xs:complexType>

  <xs:complexType name="NormalLayout">
    <xs:sequence>
      <xs:element type="LogicalElement" name="Left"  />
      <xs:element type="LogicalElement" name="Right"  />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ThreePackLayout">
    <xs:sequence>
      <xs:element type="LogicalElement" name="LogicalElement" maxOccurs="3" minOccurs="3"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SixPackLayout">
    <xs:sequence>
      <xs:element type="LogicalElement" name="LogicalElement" maxOccurs="6" minOccurs="6"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="localizationKey" use="required"/>
    <xs:attribute type="xs:string" name="localization" use="required"/>
  </xs:complexType>

  <xs:complexType name="StarLayout">
    <xs:sequence>
      <xs:element type="LogicalElement" name="Top"/>
      <xs:element type="LogicalElement" name="Left"/>
      <xs:element type="LogicalElement" name="Right"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="SkillLayout">
    <xs:sequence>
      <xs:element type="Skill" name="LeftSkill" />
      <xs:element type="Skill" name="RightSkill" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Skill">
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="CustomLayout">
    <xs:sequence>
      <xs:element type="Elements" name="Left" />
      <xs:element type="Elements" name="Right"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Elements">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element type="LogicalElement" name="LogicalElement" />
        <xs:element type="CustomCheckBoxVisualGroup" name="CustomCheckBoxVisualGroup"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CustomCheckBoxVisualGroup">
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="Main">
    <xs:sequence>
      <xs:element type="VisualOrganizationGroup" name="VisualOrganizationGroup" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Vasolik/AcsGenerator/AcsGenerator/layout.xml
<?xml version="1.0" encoding="utf-8"?>
<Main xmlns="http://www.vipl.in.rs/layout"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.vipl.in.rs/layout layout.xsd">
    <VisualOrganizationGroup name="any_trait_of_kind"
                             localization="Trait groups">
        <NormalLayout>
            <Left name="acs_filter_trait_any_sinful"/>
            <Right name="acs_filter_trait_any_virtuous"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="acs_filter_trait_any_sinful_by_their_standard"/>
            <Right name="acs_filter_trait_any_virtuous_by_their_standard"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="acs_filter_trait_any_bad_genetic"/>
            <Right name="acs_filter_trait_any_good_genetic"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="acs_filter_trait_any_commander"/>
            <Right name="acs_filter_trait_any_lifestyle"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="acs_filter_trait_any_infamous"/>
            <Right name="acs_filter_trait_any_diseases"/>
        </NormalLayout>
    </VisualOrganizationGroup>
    <VisualOrganizationGroup name="physical"
        localization="[GetTrait( 'beauty_bad_1' ).GetTraitCategoryLabel]">
        <SixPackLayout localizationKey = "acs_beauty" localization="Beauty">
            <LogicalElement name="beauty_bad_3"/>
            <LogicalElement name="beauty_bad_2"/>
            <LogicalElement name="beauty_bad_1"/>
            <LogicalElement name="beauty_good_1"/>
            <LogicalElement name="beauty_good_2"/>
            <LogicalElement name="beauty_good_3"/>
        </SixPackLayout>
        <SixPackLayout localizationKey = "acs_intellect" localization="Intellect">
            <LogicalElement name="intellect_bad_3"/>
            <LogicalElement name="intellect_bad_2"/>
            <LogicalElement name="intellect_bad_1"/>
            <LogicalElement name="intellect_good_1"/>
            <LogicalElement name="intellect_good_2"/>
            <LogicalElement name="intellect_good_3"/>
        </SixPackLayout>
        <SixPackLayout localizationKey = "acs_physique" localization="Physique">
            <LogicalElement name="physique_bad_3"/>
            <LogicalElement name="physique_bad_2"/>
            <LogicalElement name="physique_bad_1"/>
            <LogicalElement name="physique_good_1"/>
            <LogicalElement name="physique_good_2"/>
            <LogicalElement name="physique_good_3"/>
        </SixPackLayout>
        <NormalLayout>
            <Left name="pure_blooded"/>
            <Right name="fecund"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="strong"/>
            <Right name="shrewd"/>
        </NormalLayout>
        <ThreePackLayout>
            <LogicalElement name="clubfooted"/>
            <LogicalElement name="hunchbacked"/>
            <LogicalElement name="lisping"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="stuttering"/>
            <LogicalElement name="dwarf"/>
            <LogicalElement name="giant"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="inbred"/>
            <LogicalElement name="weak"/>
            <LogicalElement name="dull"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="impotent"/>
            <LogicalElement name="spindly"/>
            <LogicalElement name="scaly"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="albino"/>
            <LogicalElement name="wheezing"/>
            <LogicalElement name="bleeder"/>
        </ThreePackLayout>
    </VisualOrganizationGroup>
    <VisualOrganizationGroup name="personality"
                             localization="[GetTrait( 'lustful' ).GetTraitCategoryLabel]">
        <NormalLayout>
            <Left name="lustful"/>
            <Right name="chaste"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="gluttonous"/>
            <Right name="temperate"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="greedy"/>
            <Right name="generous"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="lazy"/>
            <Right name="diligent"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="wrathful"/>
            <Right name="calm"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="impatient"/>
            <Right name="patient"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="arrogant"/>
            <Right name="humble"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="deceitful"/>
            <Right name="honest"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="craven"/>
            <Right name="brave"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="shy"/>
            <Right name="gregarious"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="ambitious"/>
            <Right name="content"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="arbitrary"/>
            <Right name="just"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="cynical"/>
            <Right name="zealous"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="paranoid"/>
            <Right name="trusting"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="stubborn"/>
            <Right name="fickle"/>
        </NormalLayout>
        <NormalLayout>
            <Left name="vengeful"/>
            <Right name="forgiving"/>
        </NormalLayout>
        <StarLayout>
            <Top name="callous"/>
            <Left name="sadistic"/>
            <Right name="compassionate"/>
        </StarLayout>
    </VisualOrganizationGroup>
    <VisualOrganizationGroup name="personality_child" localization="[GetTrait( 'rowdy' ).GetTraitCategoryLabel]">
        <ThreePackLayout>
            <LogicalElement name="rowdy"/>
            <LogicalElement name="charming"/>
            <LogicalElement name="curious"/>
        </ThreePackLayout>
        <NormalLayout>
            <Left name="pensive"/>
            <Right name="bossy"/>
        </NormalLayout>
    </VisualOrganizationGroup>
    <VisualOrganizationGroup name="education" localization="[GetTrait( 'education_intrigue_1' ).GetTraitCategoryLabel]">
        <SkillLayout>
            <LeftSkill name="diplomacy"/>
            <RightSkill name="martial"/>
        </SkillLayout>
        <SkillLayout>
            <LeftSkill name="stewardship"/>
            <RightSkill name="intrigue"/>
        </SkillLayout>
        <SkillLayout>
            <LeftSkill name="learning"/>
            <RightSkill name="prowess"/>
        </SkillLayout>
    </VisualOrganizationGroup>
    <VisualOrganizationGroup name="commander" localization="[GetTrait( 'logistician' ).GetTraitCategoryLabel]">
        <ThreePackLayout>
            <LogicalElement name="logistician"/>
            <LogicalElement name="military_engineer"/>
            <LogicalElement name="reckless"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="jungle_stalker"/>
            <LogicalElement name="forder"/>
            <LogicalElement name="flexible_leader"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="desert_warrior"/>
            <LogicalElement name="unyielding_defender"/>
            <LogicalElement name="reaver"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="holy_warrior"/>
            <LogicalElement name="aggressive_attacker"/>
            <LogicalElement name="organizer"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="winter_soldier"/>
            <LogicalElement name="forest_fighter"/>
            <LogicalElement name="cautious_leader"/>
        </ThreePackLayout>
        <NormalLayout>
            <Left name="open_terrain_expert"/>
            <Right name="rough_terrain_expert"/>
        </NormalLayout>
    </VisualOrganizationGroup>
    <VisualOrganizationGroup name="health" localization="[GetTrait( 'pregnant' ).GetTraitCategoryLabel]">
       <CustomLayout>
           <Left>
               <CustomCheckBoxVisualGroup name="acs_filter_trait_health_wounded"/>
           </Left>
           <Right>
               <LogicalElement name="depressed_1"/>
               <LogicalElement name="lunatic_1"/>
               <LogicalElement name="possessed_1"/>
           </Right>
       </CustomLayout>
        <ThreePackLayout>
            <LogicalElement name="maimed"/>
            <LogicalElement name="infirm"/>
            <LogicalElement name="incapable"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="one_eyed"/>
            <LogicalElement name="one_legged"/>
            <LogicalElement name="disfigured"/>
        </ThreePackLayout>
        <ThreePackLayout>
            <LogicalElement name="sickly"/>
            <LogicalElement name="scarred"/>
            <LogicalElement name="eunuch"/>
        </ThreePackLayout>
        <NormalLayout>
            <Left name="blind"/>
            <Right name="pregnant"/>
        </NormalLayout>
    </VisualOrganizationGroup>
    <VisualOrganizationGroup name="health_diseases" localization="Diseases [GetTrait( 'bubonic_plague' ).GetTraitCategoryLabel]">
        <ThreePackLayout>
            <LogicalElement name="gout_ridden"/>
            <LogicalElement name="consumption"/>
